namespace ResumeApp.Resources
{
    public class ColorCodeResources
    {
        public static string CSpireEricsson = "ALPHA/NA/BLUE/1-ALPHA/NA/BLUE/2-ALPHA/NA/ORANGE/1-ALPHA/NA/ORANGE/2-ALPHA/NA/GREEN/1-ALPHA/NA/GREEN/2-ALPHA/NA/BROWN/1-ALPHA/NA/BROWN/2-ALPHA/NA/GREY/1-ALPHA/NA/GREY/2-ALPHA/NA/WHITE/1-ALPHA/NA/WHITE/2-BETA/NA/RED/1-BETA/NA/RED/2-BETA/NA/BLACK/1-BETA/NA/BLACK/2-BETA/NA/YELLOW/1-BETA/NA/YELLOW/2-BETA/NA/PURPLE/1-BETA/NA/PURPLE/2-BETA/NA/GOLD/1-BETA/NA/GOLD/2-BETA/NA/VIOLET/1-BETA/NA/VIOLET/2-GAMMA/NA/BLUE/1-GAMMA/NA/ORANGE/1-GAMMA/NA/ORANGE/2-GAMMA/NA/GREEN/1-GAMMA/NA/GREEN/2-GAMMA/NA/BROWN/1-GAMMA/NA/BROWN/2-GAMMA/NA/GREY/1-GAMMA/NA/GREY/1-GAMMA/NA/WHITE/1-GAMMA/NA/WHITE/2-GAMMA/NA/RED/1-";
        public static string SamsungClearwire = "A/LC0/Blue/1-A/LC1/Orange/1-A/LC2/Green/1-A/LC3/Brown/1-A/LC4/Slate/1-A/LC5/White/1-A/LC6/Red/1-A/LC7/Black/1-B/LC0/Blue/1-B/LC1/Orange/1-B/LC2/Green/1-B/LC3/Brown/1-B/LC4/Slate/1-B/LC5/White/1-B/LC6/Red/1-B/LC7/Black/1-G/LC0/Blue/1-G/LC1/Orange/1-G/LC2/Green/1-G/LC3/Brown/1-G/LC4/Slate/1-G/LC5/White/1-G/LC6/Red/1-G/LC7/Black/1-";
        public static string SprintAlcatelLucent = "Alpha/F1/Blue/1-Alpha/F1/Orange/1-Alpha/F2/Blue/1-Alpha/F2/Orange/1-Alpha/F3/Blue/1-Alpha/F3/Orange/1-Alpha/F4/Blue/1-Alpha/F4/Orange/1-Alpha/F5/Blue/1-Alpha/F5/Orange/1-Beta/F1/Blue/1-Beta/F1/Orange/1-Beta/F2/Blue/1-Beta/F2/Orange/1-Beta/F3/Blue/1-Beta/F3/Orange/1-Beta/F4/Blue/1-Beta/F4/Orange/1-Beta/F5/Blue/1-Beta/F5/Orange/1-Gamma/F1/Blue/1-Gamma/F1/Orange/1-Gamma/F2/Blue/1-Gamma/F2/Orange/1-Gamma/F3/Blue/1-Gamma/F3/Orange/1-Gamma/F4/Blue/1-Gamma/F4/Orange/1-Gamma/F5/Blue/1-Gamma/F5/Orange/1-";
        public static string SprintALU = "S1/NA/Orange/1-S1/NA/Yellow/1-S1/NA/Purple/1-S1/NA/Red/1-S1/NA/Blue/1-S1/NA/Green/1-S2/NA/Orange/1-S2/NA/Yellow/1-S2/NA/Purple/1-S2/NA/Red/1-S2/NA/Blue/1-S2/NA/Green/1-S3/NA/Orange/1-S3/NA/Yellow/1-S3/NA/Purple/1-S3/NA/Red/1-S3/NA/Blue/1-S3/NA/Green/1-";
        public static string SprintEricsson = "A/NA/Black/1-A/NA/White/1-A/NA/Yellow/1-A/NA/Blue/1-A/NA/Green/1-A/NA/Red/1-B/NA/Black/1-B/NA/White/1-B/NA/Yellow/1-B/NA/Blue/1-B/NA/Green/1-B/NA/Red/1-G/NA/Black/1-G/NA/White/1-G/NA/Yellow/1-G/NA/Blue/1-G/NA/Green/1-G/NA/Red/1-";
        public static string SprintNokiaMIMO = "ALPHA/GREEN/GREEN/1-ALPHA/GREEN/BLUE/1-ALPHA/GREEN/RED/1-ALPHA/GREEN/YELLOW/1-ALPHA/GREEN/ORANGE/1-ALPHA/GREEN/VIOLET/1-ALPHA/GREEN/BROWN/1-ALPHA/GREEN/WHITE/1-ALPHA/BLUE/GREEN/1-ALPHA/BLUE/BLUE/1-ALPHA/BLUE/RED/1-ALPHA/BLUE/YELLOW/1-ALPHA/BLUE/ORANGE/SPARE-ALPHA/BLUE/VIOLET/SPARE-ALPHA/BLUE/BROWN/SPARE-ALPHA/BLUE/WHITE/SPARE-BETA/RED/GREEN/1-BETA/RED/BLUE/1-BETA/RED/RED/1-BETA/RED/YELLOW/1-BETA/RED/ORANGE/1-BETA/RED/VIOLET/1-BETA/RED/BROWN/1-BETA/RED/WHITE/1-BETA/YELLOW/GREEN/1-BETA/YELLOW/BLUE/1-BETA/YELLOW/RED/1-BETA/YELLOW/YELLOW/1-BETA/YELLOW/ORANGE/SPARE-BETA/YELLOW/VIOLET/SPARE-BETA/YELLOW/BROWN/SPARE-BETA/YELLOW/WHITE/SPARE-GAMMA/VIOLET/GREEN/1-GAMMA/VIOLET/BLUE/1-GAMMA/VIOLET/RED/1-GAMMA/VIOLET/YELLOW/1-GAMMA/VIOLET/ORANGE/1-GAMMA/VIOLET/VIOLET/1-GAMMA/VIOLET/BROWN/1-GAMMA/VIOLET/WHITE/1-GAMMA/ORANGE/GREEN/1-GAMMA/ORANGE/BLUE/1-GAMMA/ORANGE/RED/1-GAMMA/ORANGE/YELLOW/1-GAMMA/ORANGE/ORANGE/SPARE-GAMMA/ORANGE/VIOLET/SPARE-GAMMA/ORANGE/BROWN/SPARE-GAMMA/ORANGE/WHITE/SPARE-";
        public static string SprintNSN = "ALPHA/NA/BLACK/SP-ALPHA/NA/RED/SP-ALPHA/NA/BLUE/1-ALPHA/NA/ORANGE/1-ALPHA/NA/GREEN/1-ALPHA/NA/BROWN/1-ALPHA/NA/SLATE/1-ALPHA/NA/WHITE/1-BETA/BROWN/SLATE/SP-BETA/GREEN/BROWN/SP-BETA/NA/YELLOW/1-BETA/NA/VIOLET/1-BETA/NA/ROSE/1-BETA/NA/AQUA/1-BETA/BLUE/ORANGE/1-BETA/ORANGE/GREEN/1-GAMMA/AQUA/BLUE/SP-GAMMA/ROSE/AQUA/SP-GAMMA/SLATE/WHITE/1-GAMMA/WHITE/RED/1-GAMMA/RED/BLACK/1-GAMMA/BLACK/YELLOW/1-GAMMA/YELLOW/VIOLET/1-GAMMA/VIOLET/ROSE/1";
        public static string SprintSamsung = "S1/RED/SLATE/1-S1/BLACK/BLUE/1-S1/BLACK/GREEN/1-S1/BLACK/BROWN/1-S1/BLACK/SLATE/1-S1/BLUE/BLUE/1-S1/BLUE/ORANGE/1-S1/BLUE/GREEM/1-S1/BLUE/BROWN/1-S1/BLUE/SLATE/1-S1/WHITE/BLUE/1-S1/WHITE/ORANGE/1-S1/WHITE/GREEN/1-S1/WHITE/BROWN/1-S1/WHITE/SLATE/1-S2/RED/BLUE/1-S2/RED/ORANGE/1-S2/RED/GREEN/1-S2/RED/BROWN/1-S2/RED/SLATE/1-S2/BLACK/ORANGE/1-S2/BLACK/GREEN/1-S2/BLACK/BROWN/1-S2/BLACK/SLATE/1-S2/BLUE/BLUE/1-S2/BLUE/ORANGE/1-S2/BLUE/GREEN/1-S2/BLUE/BROWN/1-S2/BLUE/SLATE/1-S2/WHITE/BLUE/1-S2/WHITE/ORANGE/1-S2/WHITE/GREEN/1-S2/WHITE/BROWN/1-S2/WHITE/SLATE/1-S3/RED/BLUE/1-S3/RED/ORANGE/1-S3/RED/GREEN/1-S3/RED/BROWN/1-S3/RED/SLATE/1-S3/BLACK/ORANGE/1-S3/BLACK/GREEN/1-S3/BLACK/BROWN/1-S3/BLACK/SLATE/1-S3/BLUE/BLUE/1-S3/BLUE/ORANGE/1-S3/BLUE/GREEN/1-S3/BLUE/BROWN/1-S3/BLUE/SLATE/1-S3/WHITE/BLUE/1-S3/WHITE/ORANGE/1-S3/WHITE/GREEN/1-S3/WHITE/BROWN/1-S3/WHITE/SLATE/1-";
        public static string SprintSamsungExistingPost = "S1/Blue/Blue/1-S1/Blue/Orange/1-S1/Blue/Green/1-S1/Blue/Brown/1-S1/Blue/Slate/1-S1/White/Blue/1-S1/White/Orange/1-S1/White/Green/1-S1/White/Brown/1-S1/White/Slate/1-S2/Blue/Blue/1-S2/Blue/Orange/1-S2/Blue/Green/1-S2/Blue/Brown/1-S2/Blue/Slate/1-S2/White/Blue/1-S2/White/Orange/1-S2/White/Green/1-S2/White/Brown/1-S2/White/Slate/1-S3/Blue/Blue/1-S3/Blue/Orange/1-S3/Blue/Green/1-S3/Blue/Brown/1-S3/Blue/Slate/1-S3/White/Blue/1-S3/White/Orange/1-S3/White/Green/1-S3/White/Brown/1-S3/White/Slate/1-";
        public static string SprintSamsungExistingPre = "S1/Blue/Blue/1-S1/Blue/Orange/1-S1/Blue/Green/1-S1/Blue/Brown/1-S1/Blue/Slate/1-S1/White/Blue/1-S1/White/Orange/1-S1/White/Green/1-S1/White/Brown/1-S1/White/Slate/1-S2/Blue/Blue/1-S2/Blue/Orange/1-S2/Blue/Green/1-S2/Blue/Brown/1-S2/Blue/Slate/1-S2/White/Blue/1-S2/White/Orange/1-S2/White/Green/1-S2/White/Brown/1-S2/White/Slate/1-S3/Blue/Blue/1-S3/Blue/Orange/1-S3/Blue/Green/1-S3/Blue/Brown/1-S3/Blue/Slate/1-S3/White/Blue/1-S3/White/Orange/1-S3/White/Green/1-S3/White/Brown/1-S3/White/Slate/1-";
        public static string SprintSamsungHiCap = "S1/Yellow/Blue/1-S1/Yellow/Orange/1-S1/Yellow/Green/1-S1/Yellow/Brown/1-S1/Yellow/Slate/1-S1/Yellow/Black/1-S2/Green/Blue/1-S2/Green/Orange/1-S2/Green/Green/1-S2/Green/Brown/1-S2/Green/Slate/1-S2/Green/Black/1-S3/Blue/Blue/1-S3/Blue/Orange/1-S3/Blue/Green/1-S3/Blue/Brown/1-S3/Blue/Slate/1-S3/Blue/Black/1-Spare/White/Blue/1-Spare/White/Orange/1-Spare/White/Green/1-Spare/White/Brown/1-Spare/White/Slate/1-Spare/White/Black/1-";
        public static string SprintSamsungNewPost = "S1/Blue/Blue/1-S1/Blue/Green/1-S1/Blue/Orange/1-S1/White/Blue/1-S1/White/Green/1-S1/White/Orange/1-S2/Blue/Blue/1-S2/Blue/Green/1-S2/Blue/Orange/1-S2/White/Blue/1-S2/White/Green/1-S2/White/Orange/1-S3/Blue/Blue/1-S3/Blue/Green/1-S3/Blue/Orange/1-S3/White/Blue/1-S3/White/Green/1-S3/White/Orange/1-";
        public static string SprintSamsungNewPre = "S1/Blue/Blue/1-S1/Blue/Green/1-S1/Blue/Orange/1-S1/Blue/Gray/1-S1/Blue/White/1-S1/Blue/Brown/1-S1/White/Blue/1-S1/White/Green/1-S1/White/Orange/1-S1/White/Gray/1-S1/White/White/1-S1/White/Brown/1-S2/Blue/Blue/1-S2/Blue/Green/1-S2/Blue/Orange/1-S2/Blue/Gray/1-S2/Blue/White/1-S2/Blue/Brown/1-S2/White/Blue/1-S2/White/Green/1-S2/White/Orange/1-S2/White/Gray/1-S2/White/White/1-S2/White/Brown/1-S3/Blue/Blue/1-S3/Blue/Green/1-S3/Blue/Orange/1-S3/Blue/Gray/1-S3/Blue/White/1-S3/Blue/Brown/1-S3/White/Blue/1-S3/White/Green/1-S3/White/Orange/1-S3/White/Gray/1-S3/White/White/1-S3/White/Brown/1-";
        public static string TMobile = "ALPHA/NA/BLUE/1-ALPHA/NA/BLUE/2-Alpha/NA/ORANGE/1-Alpha/NA/ORANGE/2-ALPHA/NA/GREEN/1-ALPHA/NA/GREEN/2-ALPHA/NA/BROWN/1-ALPHA/NA/BROWN/2-ALPHA/NA/GREY/1-ALPHA/NA/GREY/2-ALPHA/NA/WHITE/1-ALPHA/NA/WHITE/2-BETA/NA/RED/1-BETA/NA/RED/2-BETA/NA/BLACK/1-BETA/NA/BLACK/2-BETA/NA/YELLOW/1-BETA/NA/PURPLE/1-BETA/NA/YELLOW/2-BETA/NA/PURPLE/2-BETA/NA/GOLD/1-BETA/NA/GOLD/2-BETA/NA/VIOLET/1-BETA/NA/VIOLET/2-GAMMA/NA/BLUE/1-GAMMA/NA/ORANGE/1-GAMMA/NA/ORANGE/2-GAMMA/NA/GREEN/1-GAMMA/NA/GREEN/2-GAMMA/NA/BROWN/1-GAMMA/NA/BROWN/2-GAMMA/NA/GREY/1-GAMMA/NA/GREY/2-GAMMA/NA/WHITE/1-GAMMA/NA/WHITE/2-GAMMA/NA/RED/1-";
        public static string TMobileEricsson = "Alpha/NA/Red/1-Alpha/NA/Green/1-Alpha/NA/Blue/1-Alpha/NA/Yellow/1-Alpha/NA/White/1-Alpha/NA/Black/1-Beta/NA/Red/1-Beta/NA/Green/1-Beta/NA/Blue/1-Beta/NA/Yellow/1-Beta/NA/White/1-Beta/NA/Black/1-Gamma/NA/Red/1-Gamma/NA/Green/1-Gamma/NA/Blue/1-Gamma/NA/Yellow/1-Gamma/NA/White/1-Gamma/NA/Black/1";
        public static string TMobileEricsson5G = "ALPHA/NA/RED/A-ALPHA/NA/RED/B-ALPHA/NA/GREEN/A-ALPHA/NA/GREEN/B-BETA/NA/BLUE/A-BETA/NA/BLUE/B-BETA/NA/YELLOW/A-BETA/NA/YELLOW/B-GAMMA/NA/WHITE/A-GAMMA/NA/WHITE/B-GAMMA/NA/BLACK/A-GAMMA/NA/BLACK/B-SPARE/RED/WHITE/A-SPARE/RED/WHITE/B-SPARE/GREEN/WHITE/A-SPARE/GREEN/WHITE/B-SPARE/BLUE/WHITE/A-SPARE/BLUE/WHITE/B-SPARE/YELLOW/WHITE/A-SPARE/YELLOW/WHITE/B-SPARE/WHITE/WHITE/A-SPARE/WHITE/WHITE/B-SPARE/BLACK/WHITE/A-SPARE/BLACK/WHITE/B-";
        public static string TMobileNokia = "NA/NA/Blue/1-NA/NA/Orange/1-NA/NA/Green/1-NA/NA/Brown/1-NA/NA/Grey/1-NA/NA/White/1-NA/NA/Red/1-NA/NA/Black/1-NA/NA/Yellow/1-NA/NA/Purple/1-NA/NA/Tan/1-NA/NA/Pink/1-NA/Blue/Orange/1-NA/Orange/Green/1-NA/Green/Brown/1-NA/Brown/Grey/1-NA/Grey/White/1-NA/White/Red/1-";
    }
}